# Generated by Django 4.1.7 on 2023-03-31 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_item_current_bid_alter_item_starting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='start_time',
        ),
        migrations.AddField(
            model_name='item',
            name='ending_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='item',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
